name: build
env:
  app_name: ${{ github.event.repository.name }}
on:
  push:
    branches: ["**"]

  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests with coverage
        run: make test

      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build the release binary
        run: make release

      - name: Upload the binary as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.app_name }}
          path: target/release/${{ env.app_name }}
