name: build
env:
  app_name: ${{ github.event.repository.name }}
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test
      - name: make
        run: make
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.app_name }}
          path: target/${{ env.app_name }}
